Repository eoscostarica/evodex, pull requests merged in 2020-10, with the labels that each got.

#216 fix(wallets): remove broken wallet integrations
  src/containers/Main/Main.js
  src/ual.js
Labels: dont-merge, wallets

#228 Add Russian translation
  package.json
  src/components/LanguageSelector/LanguageSelector.js
  src/language/index.js
  src/language/ru/about.md
  src/language/ru/faq.md
  src/language/ru/ru.json
  src/utils/getMarkdownByLanguage.js
Labels: i18n

#233 fix: calculation for you give input from you receive
  src/components/InputTextAndSelect/InputTextAndSelect.js
  src/language/en/en.json
  src/language/es/es.json
  src/language/ru/ru.json
  src/language/zh/zh.json
  src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js
  src/routes/Evodex/BackLayer/Exchange/HelpeText.js
  src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js
  src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js
  src/utils/evolutiondex.js
Labels: WIP
